# Generated by Django 5.1 on 2024-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_usermodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='is_block',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermodels',
            name='otp',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
