# Generated by Django 5.1 on 2024-08-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodels_is_block_usermodels_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
