# Generated by Django 5.1 on 2024-08-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodels_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
