# Generated by Django 5.1 on 2024-08-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermodels_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='username',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
