# Generated by Django 5.1 on 2024-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodels_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='user_preference',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
