# Generated by Django 5.1 on 2024-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usermodels_user_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='user_preference',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
