# Generated by Django 5.0.7 on 2024-08-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_country_userprofile_is_verified_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelleaderform',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proof'),
        ),
    ]
