# Generated by Django 5.0.7 on 2024-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_travelleaderform_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelleaderform',
            name='mobile',
            field=models.BigIntegerField(default=8),
            preserve_default=False,
        ),
    ]
