# Generated by Django 5.0.7 on 2024-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_travelleaderform_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelleaderform',
            name='visited_countries',
            field=models.ManyToManyField(blank=True, related_name='visited_by', to='users.country'),
        ),
    ]
