# Generated by Django 5.0.7 on 2024-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_travelleaderform_visited_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelleaderform',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
