# Generated by Django 5.0.7 on 2024-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_travelleaderform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelleaderform',
            name='visited_countries',
            field=models.ManyToManyField(null=True, related_name='visited_by', to='users.country'),
        ),
    ]
