# Generated by Django 5.0.7 on 2024-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_travelleaderform_visited_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelleaderform',
            name='visited_countries',
            field=models.ManyToManyField(related_name='visited_by', to='users.country'),
        ),
    ]
