# Generated by Django 5.0.7 on 2024-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_usermodels_is_approve_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelleaderform',
            name='is_approved',
            field=models.CharField(default='pending', max_length=254),
        ),
    ]
