# Generated by Django 5.0.7 on 2024-08-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_travelleaderform_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
