# Generated by Django 5.0.7 on 2024-08-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_usermodels_otp_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodels',
            name='otp_expiration',
        ),
    ]
