# Generated by Django 5.0.7 on 2024-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_usermodels_address_remove_usermodels_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
