# Generated by Django 5.0.7 on 2024-08-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_trips_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='type_of_Trip',
            new_name='type',
        ),
    ]
