# Generated by Django 5.0.7 on 2024-08-31 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_rename_type_of_trip_trips_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='type',
            new_name='trip_type',
        ),
    ]
