# Generated by Django 5.0.7 on 2024-08-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_rename_type_trips_trip_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
