# Generated by Django 5.0.7 on 2024-08-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_enddate_trips_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='participant_Limit',
            new_name='participant_limit',
        ),
    ]
