# Generated by Django 5.0.7 on 2024-08-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_participant_limit_trips_participant_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='accommodation',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
