# Generated by Django 5.0.7 on 2024-09-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_rename_image_trips_trip_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trips'),
        ),
    ]
