# Generated by Django 5.0.7 on 2024-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_of_trip',
            field=models.CharField(blank=True, null=True),
        ),
    ]
