# Generated by Django 5.0.7 on 2024-09-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_post_type_of_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
