# Generated by Django 5.0.7 on 2024-09-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_payment_intent',
        ),
    ]
