# Generated by Django 5.0.7 on 2024-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_remove_payment_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='is_completed',
            field=models.CharField(default='pending', max_length=254),
        ),
    ]
