# Generated by Django 5.0.7 on 2024-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_userprofile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default=44, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='ongoing', max_length=10),
        ),
    ]
