# Generated by Django 5.0.7 on 2024-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
