# Generated by Django 5.0.7 on 2024-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_chatmessages_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Ongoing', max_length=355),
        ),
    ]
