# Generated by Django 5.0.7 on 2024-10-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='is_refund',
            field=models.CharField(default='false'),
        ),
    ]
