# Generated by Django 5.0.7 on 2024-10-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_remove_notification_message_notification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodels',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
