# Generated by Django 5.0.7 on 2024-10-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_place_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='is_group',
            field=models.CharField(default='false'),
        ),
    ]
