# Generated by Django 5.0.7 on 2024-10-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_userreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreport',
            name='created_at',
        ),
    ]
