services:
  web:
    build: .
    command: ["gunicorn", "--bind", ":8000", "travello_backend.wsgi:application"]
    volumes:
      - .:/app
      - media_volume:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - travello_backend-network

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    networks:
      - travello_backend-network


 

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - travello_backend-network
      
  daphne:
    build: .
    command: daphne -b 0.0.0.0 -p 8001 travello_backend.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      # - web
      - redis
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=travello_backend.settings
    networks:
      - travello_backend-network

  

volumes:
  db_data:
  media_volume:

networks:
  travello_backend-network:
    driver: bridge